env-validation
Q-Devs-ng/bartimeus pull request #3
Opened 2022-07-24 18:09 UTC by bolubee101

### env-validation
Updated env validation with the following
- REDIS_URL: string
- MONGODB_URL: string
- JWT_SECRET: string

2022-07-24 18:28 UTC, Emmanuerl commented
> ### env-validation
> Updated env validation with the following
> 
> * REDIS_URL: string
> * MONGODB_URL: string
> * JWT_SECRET: string

@bolubee101 we're currently trying to achieve https://docs.nestjs.com/techniques/configuration . We've setup the schema, quite alright, what's remaining is for us to configure the ConfigModule and make the ConfigService injectable

Also, you might also want to add an environment map somewhere so we don't have things like
 ```javascript
this.configService.get("JWT_SECRET");
``` 
but rather 
```typescript
this.configService.get(keys.jwt.secret);
```

2022-07-24 18:29 UTC, Emmanuerl requested changes
https://github.com/Q-Devs-ng/bartimeus/pull/3#issuecomment-1193370530

2022-07-26 08:05 UTC, Emmanuerl requested changes
I also can't see the URI scheme validation for mongodb and redis

2022-07-26 08:05 UTC, Emmanuerl commented on src/app.module.ts
> +      envFilePath: '.development.env',
why is this .development.env ?

2022-07-26 08:08 UTC, bolubee101 commented on src/app.module.ts
> +      envFilePath: '.development.env',
I would update it.

2022-07-26 09:28 UTC, Emmanuerl approved these changes

2022-07-26 09:28 UTC, merged